import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class StrangeCountryTest {

	protected StrangeCountry solution;

	@Before
	public void setUp() {
		solution = new StrangeCountry();
	}

	@Test(timeout = 2000)
	public void testCase0() {
		String[] g = new String[] { "NY", "YN" };

		int expected = 0;
		int actual = solution.transform(g);

		Assert.assertEquals(expected, actual);
	}

	@Test(timeout = 2000)
	public void testCase1() {
		String[] g = new String[] { "NYYNN", "YNYNN", "YYNNN", "NNNNY", "NNNYN" };

		int expected = 1;
		int actual = solution.transform(g);

		Assert.assertEquals(expected, actual);
	}

	@Test(timeout = 2000)
	public void testCase2() {
		String[] g = new String[] { "NYYNNNN", "YNYNNNN", "YYNNNNN", "NNNNYYN", "NNNYNYY", "NNNYYNY", "NNNNYYN" };

		int expected = 1;
		int actual = solution.transform(g);

		Assert.assertEquals(expected, actual);
	}

	@Test(timeout = 2000)
	public void testCase3() {
		String[] g = new String[] { "NYNYNNNNNNNN", "YNYNNNNNNNNN", "NYNYYNNNNNNN", "YNYNNNNNNNNN", "NNYNNYYNNNNN", "NNNNYNYNNNNN", "NNNNYYNNNNNN", "NNNNNNNNYYNN", "NNNNNNNYNYNN",
				"NNNNNNNYYNNN", "NNNNNNNNNNNY", "NNNNNNNNNNYN" };

		int expected = 2;
		int actual = solution.transform(g);

		Assert.assertEquals(expected, actual);
	}

	@Test(timeout = 2000)
	public void testCase4() {
		String[] g = new String[] { "NYNNNN", "YNYNNN", "NYNYNN", "NNYNNN", "NNNNNY", "NNNNYN" };

		int expected = -1;
		int actual = solution.transform(g);

		Assert.assertEquals(expected, actual);
	}

	@Test(timeout = 2000)
	public void testCase5() {
		String[] g = new String[] { "NYNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYYYNN", "YNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYYYNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNN",
				"NNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNN",
				"NNNNNNNNNNNNNYNNNNNNNNNNNNNNYNNNNNNNNNNNNNNN", "YNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYYYNN", "NNNNNNNNNYNNNNNNNNNNNNNNNYYNNNNNNNNNNNNNNNNN",
				"NNNNNNNNYNNNYNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNYNNNNNNNYNNNNNNNNNNNNNNNNNNNNNN",
				"NNNNNNNNNYNNNNNNNNNNNNNNNYYNNNNNYNNNNNNNNNNN", "NNNNNNYNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNYNNNYNNNNNNNNNNNNNNNNNNN",
				"NNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNYNNNNNNNNY", "NNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNYNNNNNN", "NNNNNNNNNNYNNNNYNNNNNNNNNNNNNNNNNNYNNNNNNNNY",
				"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNYN", "NNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
				"NNNNNNNNNNNYNNNNNNNNNNNNNNNNNYNNNNNNYNYNNNNN", "NNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNYNNYNNNNNNNNNNNNN",
				"NNNNNNNNNNNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNYNNNYYNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNYNNNYNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNN",
				"NNNNNNNNNNNNNNNNNNNNNNNYNNNNNNYNNNNNNNNNNNNN", "NNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNN",
				"NNNNNNNNNNNNNNNNNNNNNNNYNNNYNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNYN", "NNNNNNNNNNNNYNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNN",
				"NNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNYNNNNNNNN", "NNNNNNNNNNNNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNN",
				"NNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNYNNNNN", "NNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNYNNNNNNN",
				"YYNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYYNN", "YYNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNYNN", "YYNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYYNNN",
				"NNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNYNNNNNNNNNNNN", "NNNNNNNNNNYNNNNYNYNNNNNNNNNNNNNNNNNNNNNNNNNN" };

		int expected = -1;
		int actual = solution.transform(g);

		Assert.assertEquals(expected, actual);
	}

}
